project1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project_app.urls')),
]

project_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
 
urlpatterns = [
    path('', views.main),
    path('cc_test/', views.cc_test),
    url(r'^joinClass/.+$',views.joinClass),
    path('inputClass/', views.inputClass),
    path('main/', views.main),
    path('logout/', views.logout),
    path('login/', views.login),
    path('get_in_class_list/', views.get_in_class_list),
    #path('register/', views.register),
    #path('pdf_upload/', views.pdf_upload),
    #path('pdf/', views.pdf),

    path('updateChat/', views.updateChat),
    path('sendChat/', views.sendChat),
    path('ddabong/', views.ddabong),
    path('delete_msg/', views.delete_msg),
    path('create_class/', views.create_class),
    path('check_class/', views.check_class),
    path('check_login/', views.check_login),
    path('check_set_name/', views.check_set_name),
    path('save_memo/', views.save_memo),
    path('delete_user_list/', views.delte_user_list),
    path('delete_pdf/', views.delete_pdf),
    path('check_class_id/', views.check_class_id),

    path('join/', views.join),
    path('check_id/', views.check_id),
    path('join/register_member_db/',views.main),

    path('password-change/', views.password_change),
    path('check_validation/', views.check_validation),
    path('password_change_success/', views.password_change_success),
    path('mypage/', views.mypage),
    path('upload/', views.upload_class),
    url(r'^password_validation_check/.+$',views.password_validation_check),
    url(r'^psw_changed_success/.+$',views.psw_changed_success),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_app/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class ChatNode(models.Model) :

	chat_unique_id = models.AutoField(primary_key=True)
	user_id = models.CharField(max_length=50, default="unknown")
	user_name = models.CharField(max_length=50, default="unknown")
	content = models.CharField(max_length=500, default="")
	class_id = models.CharField(max_length=50, default="")
	created_date = models.CharField(max_length=50,default=datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
	ddabong = models.IntegerField(default=0)

	def __str__(self) :
		return self.content


class PDF(models.Model) :

	pdf_name = models.CharField(max_length=50, default="")
	pdf_url = models.CharField(max_length=50, default="")
	class_id = models.CharField(max_length=50, default="")
	pdf = models.FileField(default='', upload_to='pdfs/')

	def __str__(self) :
		return self.pdf_url


class ClassNode(models.Model) :

	class_name = models.CharField(max_length=50, default="")
	class_id = models.CharField(max_length=50, default="")
	founder_id = models.CharField(max_length=50, default="")
	founder_name = models.CharField(max_length=50, default="")
	created_date = models.CharField(max_length=50,default=datetime.now().strftime("%Y-%m-%d"))
	image = models.ImageField(upload_to='classImg/', default='classImg/LYAN1.jpg')
	number_of_user = models.IntegerField(default=0)
	user_list = models.TextField(default = '')

	def __str__(self) :
		return self.class_name


class Member(models.Model) :
	
	user_name = models.CharField(max_length=50, default= "")
	user_id = models.CharField(primary_key=True, max_length=50, default= "")
	user_psw = models.CharField(max_length=50, default = "")
	user_email = models.CharField(max_length=50, default= "")
	in_class_list = models.TextField(default = '')

	def __str__(self):
		return self.user_id




class Memo(models.Model) :

	user_id = models.CharField(primary_key=True, max_length=50, default= "")
	class_name = models.CharField(max_length=50, default="")
	class_id = models.CharField(max_length=50, default="")
	founder_id = models.CharField(max_length=50, default="")
	memo = models.TextField(default = '')


	def __str__(self) :
		return self.class_name + ',' + self.user_id

project_app/forms.py
from django import forms
from .models import ClassNode

class ClassNodeForm(forms.ModelForm):
	class Meta:
		model = ClassNode
		fields = {'class_name', 'class_id', 'founder_id', 'image', 'founder_name'}

project_app/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .models import *
from django.core import serializers
from datetime import datetime
from django.core.files.storage import FileSystemStorage
from django.shortcuts import redirect
import random, string
from .forms import ClassNodeForm

# Create your views here.

def index(request) :

	pdfs = PDF.objects.filter(class_id = 'A')

	context = { 'pdfs' : pdfs }

	return render(request, './chat+viewer.html', context)



def cc_test(request) :

	return render(request, './create_class.html')


def joinClass(request) :

	if request.method == 'GET' :

		#print(request.path.split('/')[2])

		class_id = request.path.split('/')[2]

		#print(class_id)

		classnode = ClassNode.objects.get(class_id = class_id)

		pdfs = PDF.objects.filter(class_id = class_id)

		if not request.session.get('login_complete', False):

			N = 8
			random_unique_id = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(N));

			user_list = []
			for item in classnode.user_list.split(',') :
			    if '[' in item :
			        item = item.replace('[', '')
			    if '\'' in item :
			        item = item.replace('\'', '')
			    if ']' in item :
			        item = item.replace(']', '')
			    user_list.append(item.strip())

			while True :
				if random_unique_id in user_list :
					random_unique_id = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(N));
				else :
					user_info = random_unique_id + '(unknown)'
					if user_info not in user_list :
						user_list.append(user_info)
					if '.' in user_list :
						user_list.remove('.')

					if '' in user_list :
						user_list.remove('')
					#print(user_list)
					classnode.user_list = user_list
					classnode.save()
					break
            
			unknown_member = Member(user_name = 'unknown', user_id = random_unique_id)

			context = { 'member' : unknown_member ,  'pdfs' : pdfs , 'classnode' : classnode }

		else :

			user_id = request.session.get('user_id', 'unknown')
			user_name = request.session.get('user_name', 'unknown')

			try :
				this_member = Member.objects.get(user_id = user_id)
				in_class_list = []
				for item in this_member.in_class_list.split(',') :
				    if '[' in item :
				        item = item.replace('[', '')
				    if '\'' in item :
				        item = item.replace('\'', '')
				    if ']' in item :
				        item = item.replace(']', '')
				    in_class_list.append(item.strip())

				if class_id not in in_class_list :
					in_class_list.append(class_id)
				if '.' in in_class_list :
					in_class_list.remove('.')
				if '' in in_class_list :
					in_class_list.remove('')

				this_member.in_class_list = in_class_list
				this_member.save()

			except :
				pass

			member = Member(user_name = user_name, user_id = user_id)

			try :
				memo = Memo.objects.get(class_id = class_id, user_id = user_id)
				context = { 'member' : member ,  'pdfs' : pdfs  , 'classnode' : classnode , 'memo' : memo}
			except :
				context = { 'member' : member ,  'pdfs' : pdfs  , 'classnode' : classnode }

			#print(context)

			#print(user_id)

			"""
			classnode = ClassNode.objects.get(class_id = class_id)
			classnode.number_of_user = classnode.number_of_user + 1
			classnode.save()
			"""


			user_list = []
			for item in classnode.user_list.split(',') :
			    if '[' in item :
			        item = item.replace('[', '')
			    if '\'' in item :
			        item = item.replace('\'', '')
			    if ']' in item :
			        item = item.replace(']', '')
			    user_list.append(item.strip())


			user_info = user_id + "(" + user_name + ")"
			if user_info not in user_list :
				user_list.append(user_info)
			if '.' in user_list :
				user_list.remove('.')

			if '' in user_list :
				user_list.remove('')
			classnode.user_list = user_list
			classnode.save()



		return render(request, './chat+viewer.html', context)

	# PDF 등록
	if request.method == 'POST':
		class_id = request.POST.get('class_id_text', False)
		user_id = request.session.get('user_id', 'unknown')
		user_name = request.session.get('user_name', 'unknown')
		
		member = Member.objects.get(user_name = user_name, user_id = user_id)

		classnode = ClassNode.objects.get(class_id = class_id)

		for pdf in request.FILES.getlist('upload[]'):
			#print(pdf)
			print(class_id, pdf.name)
			pdf_url = "../media/pdfs/" + "[" + class_id + "]" + pdf.name
			new_pdf = PDF(pdf_name = "[" + class_id + "]" + pdf.name,
				pdf_url = pdf_url, 
				class_id = class_id, 
				pdf = pdf)
			#print(new_pdf)
			new_pdf.save()
			#fs = FileSystemStorage()
			#filename = fs.save(pdf.name, pdf)
			#uploaded_file_url = fs.url(filename)
			#print(uploaded_file_url)

		#print(request.POST.get('class_id_text', False))

		pdfs = PDF.objects.filter(class_id = class_id)

		context = { 'pdfs' : pdfs, 'member' : member, 'classnode' : classnode }

		"""
		file_get = request.POST.get('upload', False)
		if(file_get == False) :
			img_src = request.FILES['upload']
			fs = FileSystemStorage()
			filename = fs.save(img_src.name, img_src)
		"""

		return render(request, './chat+viewer.html', context)



def main(request) :

	if request.method == 'GET' :

		if not request.session.get('login_complete', False):
			unknown_member = Member(user_name='unknown', user_id = 'unknown')
			context = { 'member' : unknown_member }

		else :
			user_id = request.session.get('user_id', 'unknown')
			user_name = request.session.get('user_name', 'unknown')

			member = Member(user_name=user_name, user_id = user_id)

			context = { 'member' : member }

		return render(request, './main.html', context)

	if request.method == 'POST':

		user_name=request.POST['user_name']
		#user_name = request.POST.get('user_name', False);
		user_id = request.POST['user_id']
		user_psw = request.POST['user_psw']
		#user_email = request.POST.get('user_email', False);
		user_email=request.POST['user_email']

		new_member = Member(user_name=user_name, user_id = user_id, user_psw = user_psw, user_email=user_email)
		#멤버 객체 생성 
		new_member.save()

		context = { 'member' : new_member }

		request.session['login_complete'] = True
		request.session['user_id'] = user_id
		request.session['user_name'] = user_name

		return render(request, './main.html', context)


def logout(request) :

	request.session['login_complete'] = False

	"""
	unknown_member = Member(user_name='unknown', user_id = 'unknown')

	context = { 'member' : unknown_member }

	return render(request, './main.html', context)
	"""

	return redirect('../main/')


def check_login(request) :

	user_id = request.GET.get('id',None)
	user_psw = request.GET.get('psw',None)

	try :
		member = Member.objects.get(user_id = user_id)
		#print(user_id, user_psw, member)
		if member.user_psw != user_psw :
			result = { "result" : "psw_failed"}
		else :
			request.session['login_complete'] = True
			request.session['user_id'] = user_id
			request.session['user_name'] = member.user_name

			result = { "result" : "success" }

	except :
		result = { "result" : "id_failed" }
		
	#print(result)
	return JsonResponse(result)


def login(request) :

	user_id = request.session.get('user_id', False)
	user_name = request.session.get('user_name', False)

	#print(user_id, user_name)
	member = Member.objects.get(user_id = user_id)

	#member = Member(user_name=user_name, user_id = user_id)

	#context = { 'member' : member }

	#return render(request, './main.html', context)

	return redirect('../main/')


def register(request) :

	return render(request, './register.html')


"""
def pdf_upload(request) :

	if request.method == 'POST':
		for f in request.FILES.getlist('upload[]'):
			print(f)

		#print(request.POST.get('class_id_text', False))

		class_id = request.POST.get('class_id_text', False)
		pdfs = PDF.objects.filter(class_id = class_id)

		context = { 'pdfs' : pdfs }

		return render(request, './chat+viewer.html', context)
		#return redirect(request, './chat+viewer.html', context)
"""


def check_class(request) :

	try :
		class_id = request.GET.get('class_id',None)

		classnode = ClassNode.objects.get(class_id = class_id)
		result = { "result" : "success"}

	except :

		result = { "result" : "failed"}


	return JsonResponse(result)







def inputClass(request) :

	return render(request, './input_class.html')



def create_class(request) :

	if request.method == 'GET' :

		class_name = request.GET.get('class_name',None)
		class_code = request.GET.get('class_code',None)
	
		result = { "result" : "success" }

		print(class_name, class_code)

		new_class = ClassNode(class_name = class_name, class_code = class_code)
		new_class.save()

		return JsonResponse(result)

def pdf(request) :

	return render(request, './viewer_test.html')


def updateChat(request) :

	if request.method == 'GET' :

		class_id = request.GET.get('class_id',None)

		json_serializer = serializers.get_serializer("json")()
		#chats = json_serializer.serialize(ChatNode.objects.filter(class_id=class_id).order_by('ddabong').reverse(), ensure_ascii=False)
		chats = json_serializer.serialize(ChatNode.objects.filter(class_id=class_id), ensure_ascii=False)
		#chats = json_serializer.serialize(Chat.objects.all(), ensure_ascii=False)
		#chats = Chat.objects.all()

		try :
			class_user_list = ClassNode.objects.get(class_id = class_id).user_list
		except :
			class_user_list = []
	
		result = { "chats" : chats , "class_user_list" : class_user_list }

		#print(result)

		return JsonResponse(result)


def sendChat(request) :

	if request.method == 'GET' :

		now = datetime.now()
		#print(now)

		user_id = request.GET.get('user_id',None)
		user_name = request.GET.get('user_name',None)
		chat_content = request.GET.get('chat_content',None)
		class_id = request.GET.get('class_id',None)

		#print(chat_content)

		new_chat = ChatNode(user_id = user_id, user_name = user_name, content = chat_content, class_id = class_id)
		new_chat.save()
	
		result = { "result" : 'false' }

		return JsonResponse(result)

project_app/templates/create_class.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<script type="text/javascript" src="http://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>  

	<script type="text/javascript">
		function create_class(){
			var class_name = $("#class_name").val();
			var class_code = "#A";

	        $.ajax({
	          url: '/create_class/',
	          data: {
	          	  'class_name' : class_name,
	          	  'class_code' : class_code,
	          },
	          dataType: 'json',
	          success: function (data) {
	          	alert("success");
	          }
	        });
		}
	</script>
</head>
<body>
	<input type="text" id="class_name" style="width: 10%; height: 30px;">
	<button type="button" style="width: 100px; height: 50px;" onclick="create_class();">클래스 생성</button>
</body>
</html>

project_app/templates/get_in_class_list.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	{% for in_class_list in in_class_lists %}
		{{in_class_list}}<br>
	{% endfor %}
</body>
</html>

project_app/templates/input_class.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<script type="text/javascript" src="http://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>  


	<style type="text/css">
		.input_class_div{
			width: 40%;
			height: 40%;
			position: absolute;
			top: 50%;
			left: 50%;
			transform: translate(-50%,-50%);
			background-color: yellow;
		}
	</style>
	<script type="text/javascript">
		function join_class(){
			var class_id = $("#class_id").val();

			$.ajax({
	          url: '/check_class/',
	          data: {
	          	  'class_id' : class_id,
	          },
	          dataType: 'json',
	          success: function (data) {
	          	//alert(data.result);
	          	if(data.result == 'success'){
	          		var addr = '../joinClass/' + class_id;
	          		window.location.href = addr;
	          	}
	          	else {
	          		alert("존재하지 않는 클래스코드 입니다.");
	          	}
	          }
	        });
		}
	</script>
</head>
<body>
	<div class="input_class_div">
		<input type="text" id="class_id" style="width: 10vw; height: 5vw;">
		<button type="button" style="width: 5vw; height: 5vw;" onclick="join_class();">접속</button>
	</div>
</body>
</html>

project_app/templates/join.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>IHAQ_join</title>
	<link rel="stylesheet" href="main.css">
	<script type="text/javascript" src="js/jquery.backstretch.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

	<script type="text/javascript">
		function showPassword() {
		    var x = document.getElementById("user_re_psw");
			    if (x.type === "password") {
			        x.type = "text";
			    } else {
			        x.type = "password";
			    }
		}

		var id_validation = 'false';
		var psw_validation = 'false';

		function check_psw(){
			var psw = $("#user_psw").val();
			var re_psw = $("#user_re_psw").val();

			if(psw == re_psw){
				$("#psw_check_result").html("PASS");
				$("#psw_check_result").css({
					'color' : 'green',
				});
				psw_validation = 'true';
			}
			else{
				$("#psw_check_result").html("Not correct");
				$("#psw_check_result").css({
					'color': 'red',
				});
				psw_validation = 'false';
			}
		}

		function check_id(){
			var user_id = $("#user_id").val();

			$.ajax({
				
				url : '/check_id/',
				data : {
					'user_id' : user_id
				},
				dataType: 'json',
			
				success: function (response_result){
					alert(response_result.result);
					
					if(response_result.result == 'true'){
						$("#id_check_result").html("중복");
						$("#id_check_result").css({
							'color' : 'red',
						});
						id_validation = 'false';
					}
					else if(response_result.result == 'false'){
						$("#id_check_result").html("사용가능");
						$("#id_check_result").css({
							'color' : 'green',
						});
						id_validation = 'true';
					}
					
				}
			});
		}

		function check_submit(){
			if(id_validation == 'true' && psw_validation == 'true'){
				var form = document.frm;
				form.action = "../main/";
				form.submit();
			}
			else if(id_validation == 'false' && psw_validation == 'true'){
				alert("아이디를 확인해주세요.");
			}
			else if(id_validation == 'true' && psw_validation == 'false'){
				alert("비밀번호를 확인해주세요.");
			}
			else{
				alert("아이디, 비밀번호를 확인해주세요");
			}
		}

	</script>
</head>
<body>
	<div id="join_page">
		<!-- 로고는 다른 글씨체를 사용해야 해서 직접 font 태그로 설정  -->
	<form method="post" name = "frm">
			<h2>회원가입</h2>
				{% csrf_token%}
		    	<p>이름 : <input type="text" id="user_name" name = "user_name" autofocus></p>
		       	<p>아이디 : <input type = "text" id = "user_id" name = "user_id">
				<button type = "button" onclick="check_id();">중복확인</button></p>
				<p id="id_check_result"></p>
				<p>비밀번호 : <input type = "password" id = "user_psw" name = "user_psw" placeholder=" 영문, 숫자 조합 6자 이상"></p>
				<p>비밀번호 확인 : <input type = "password" id ="user_re_psw" onchange="check_psw();">
				<p id = "psw_check_result"></p>

				<input type="checkbox" onclick="showPassword()"><font size="1.9">비밀번호 보기</font></p>
				<p>E-mail : <input type="text" id="user_email" name = "user_email"></p>

				<button type="button" onclick="check_submit();">확인</button>
				<button type="reset">취소</button>
			</div>
		</form>
	</div>
	
	<!-- BackStretch는 image를 어떤 사이즈여도 full screen에 맞춰줌 -->
	
	<!--
 	<script>
 		$.backstretch("img/background.png");
 	</script>
 	-->
</body>
</html>

project_app/templates/password_change.html
<!DOCTYPE html>
<html>
<head>
	<title>iHAQ | 비밀번호 찾기</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script type="text/javascript">
	function validation(){
			var id = $("#id").val();
			var email = $("#email").val(); 

			$.ajax({
	          url: '/check_validation/',
	          data: {
	          	  'id' : id,
	          	  'email' : email,
	          },
	          dataType: 'json',
	          success: function (data) {
	          	//alert(data.result);

				if(data.result == 'success'){ 
	          		var form = document.frm;
	          		form.action="../../password_change_success/";
	          		form.submit();
	          	}
	          	else if(data.result == 'id_failed'){
	          		alert("존재하지 않는 ID 입니다.");
	          	}
	          	else{
	          		alert("E-mail을 다시 확인해주세요.");
	          	}
	          }
	        });
		}
	</script>
	<style type="text/css">
		#header{
			width:100%;
			height:40px;
			margin-top: -8%;
		}
		#logo, #header{
			float:left;
		}
		#logo{
			width:14%;
			height:5vw;
			text-align: center;
			font-size:2em;
			overflow: hidden;
			background-size: 75%;
			background-repeat: no-repeat;
		}
		#logo > span{
			color:blue;
		}
		#bar{
			background-color:#03003F;
			height:30px;
			margin:1.2vh 0 0 12vw;
		}
		#findpw_div{
			border: 1px solid black;
			margin: 10% 28% 10% 28%;
		}
		#findpw_header{
			margin: 5% 5% 2% 5%;
		}
		#sendemail_button{
			margin: 5% 1% 5% 50%;
			padding: 1% 10% 1% 10%;
		}
		input{
			border: 0px;
		}
		.id_input, .email_input{
			width: 100%;
			padding-left: 20%;
			padding-top: 3%
		}
		.border-bottom{
			width: 70%;
		}
	</style>
</head>
<body>
	<div id="header">
		<a href="../">
		<div id="logo" style="background-image: url('../../static/img/logo_color.png');"></div>
		</a>
		<div id="bar"></div> 
	</div>
	<div id="findpw_div">
		<div id="findpw_header">
			<b> 비밀번호 찾기</b>
		</div>
		<div id="findpw_section1">
			
			<form method="post" name="frm" >
				{% csrf_token%}
				<div class="id_input">
					<input class="border-bottom" type="text" id="id" name="id" placeholder=" 아이디">
				</div>
				<div class="email_input">
					<input class="border-bottom" type="text" id="email" name = "email" placeholder=" E-mail">
				</div>
				<button class="btn btn-default" id="sendemail_button" type="button" onclick="validation();">메일 보내기</button>
			</form>
		</div>
	</div>
</body>
</html> 

project_app/templates/psw_changed_success.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
비밀번호가 성공적으로 변경되었습니다.
</body>
</html>

project_app/templates/upload_class.html
<!DOCTYPE html>
<html>
<head>
	<title>클래스 업로드</title>
	<link rel="stylesheet" type="text/css" href="/static/semantic/semantic.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<style type="text/css">
		#class_div{
			width:350px;
			height:500px;
			position:absolute;
			top: 50%;
			left: 50%;
			transform: translate(-50%, -50%);
			box-shadow:0px -1px 30px 2px #999;
			border-radius:10px;
			z-index: 9999;
			background-color: white;
		}
		#class_header{
			width:350px;
			height:120px;
			text-align:center;
			padding:48px 50px 10px 50px;
			font-size:1.5em;
		}
		#class_section{
			width:350px;
			height:300px;
			padding:0 0 0 40px;
		}
		#class_footer{
			width:350px;
			height:80px;
			text-align:center;
			font-size: 1.2em;
		}
		#class_name_section,#class_code_section, #class_image_section, #class_button_section{
			width:280px;
			height:60px;
		}
		#btn{
			height:38px;
		}
		#id_class_id{
			width:225px;
		}
		#btn1{
			width:280px;
			font-weight: bold;
			border-radius:5px;
		}
</style>
<script type="text/javascript">
		//할당 버튼을 누르면 클래스 고유 번호 임의로 할당
		function allocate() {
			var id = "";
			for(var i = 0; i < 8; i++) {
				var ran = randomRange(1, 2);
				switch(ran) {
				case 1: id += randomRange(0, 9); break;
				case 2: id += String.fromCharCode(randomRange(65,90)); break;
				}
			}
			document.getElementById("id_class_id").value = id;
		}

		//랜덤 번호 생성
		function randomRange(n1, n2) {
			 return Math.floor((Math.random() * (n2 - n1 + 1)) + n1);
		}


		function create_class(){
			var form = document.frm;
			if(check_class_id_flag == true){
				form.action = "../upload/";
				form.submit();
			}
			else{
				alert("클래스 코드를 확인해주세요.");
			}
		}

		var check_class_id_flag = false;

		$(document).ready(function(){
	      	$('#id_class_id').on('input',function(e){
				//alert('Changed!')
				var class_id = $("#id_class_id").val();
				//console.log(text);
				$.ajax({
					url: '/check_class_id/',
					data: {
						'class_id' : class_id,
					},
					dataType: 'json',
					success: function (data) {
						//console.log(class_id);
						if(data.result == 'success'){
							$("#class_check_text").html("사용 가능한 클래스코드 입니다.");
							$("#class_check_text").css("color", "green");
							check_class_id_flag = true;
						}
						else{
							$("#class_check_text").html("이미 사용중인 클래스코드 입니다.");
							$("#class_check_text").css("color", "red");
							check_class_id_flag = false;
						}
					}
				});
			});
	    });


</script>
</head>
<body>
<div id="class_div">
		<div id="class_header">
			<b>클래스 개설</b>
		</div>
		<div id="class_section">
			<form class="ui form" name="frm" method="post" enctype="multipart/form-data"> 
				{% csrf_token %}
				<div class="field" id="class_image_section">
					<span>
						<input type="file" name="image" accept="image/*" id="id_image">
					</span>
				</div>
				<div class="field" id="class_name_section">
					<span>
						<input type="text" name="class_name" maxlength="10" required id="id_class_name" placeholder="클래스 이름">
					</span>
				</div>
				<div class="field" id="class_code_section">
					<span id="span">
						<input type="text" name="class_id" maxlength="10" required id="id_class_id" placeholder="클래스 코드">
					</span>
					<button type="button" class="btn btn-danger" id="btn" onclick="allocate();">
						할당
					</button>
					<br>
					<div id="class_check_text" style="width: 100%; height: 40px;"></div>
				</div>
				<div  id="class_button_section" >
					<button class="btn btn-default" id="btn1" type="button" onclick="create_class();">
						클래스 생성
					</button>
				</div>
				<input type="hidden" name="founder_id" maxlength="10" required id="id_founder_id" value="{{ myself.get.user_id }}">
				<input type="hidden" name="founder_name" maxlength="10" required id="id_founder_name" value="{{ myself.get.user_name }}">
			</form>
		</div>
		<div id="class_footer">
			<a href="#">사용방법이 궁금하신가요?</a>
		</div>
	</div>
</body>
</html>